<?php
/**
 * Contact
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Print-Gateway-prod
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-09-18T08:39:50Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Contact Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Contact implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'contact';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'country' => 'string',
        'invalid_use_anyway' => 'bool',
        'last_name' => 'string',
        'city' => 'string',
        'is_valid' => 'bool',
        'sticky_slip_image_id' => 'string',
        'postcode' => 'string',
        'telephone' => 'string',
        'address_row2' => 'string',
        'chamber_of_commerce' => 'string',
        'fullstreet' => 'string',
        'first_name' => 'string',
        'is_vat_validated' => 'bool',
        'id' => 'string',
        'email' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'country' => null,
        'invalid_use_anyway' => null,
        'last_name' => null,
        'city' => null,
        'is_valid' => null,
        'sticky_slip_image_id' => null,
        'postcode' => null,
        'telephone' => null,
        'address_row2' => null,
        'chamber_of_commerce' => null,
        'fullstreet' => null,
        'first_name' => null,
        'is_vat_validated' => null,
        'id' => null,
        'email' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'country' => 'country',
        'invalid_use_anyway' => 'invalidUseAnyway',
        'last_name' => 'lastName',
        'city' => 'city',
        'is_valid' => 'isValid',
        'sticky_slip_image_id' => 'stickySlipImageId',
        'postcode' => 'postcode',
        'telephone' => 'telephone',
        'address_row2' => 'addressRow2',
        'chamber_of_commerce' => 'chamberOfCommerce',
        'fullstreet' => 'fullstreet',
        'first_name' => 'firstName',
        'is_vat_validated' => 'isVatValidated',
        'id' => 'id',
        'email' => 'email'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'country' => 'setCountry',
        'invalid_use_anyway' => 'setInvalidUseAnyway',
        'last_name' => 'setLastName',
        'city' => 'setCity',
        'is_valid' => 'setIsValid',
        'sticky_slip_image_id' => 'setStickySlipImageId',
        'postcode' => 'setPostcode',
        'telephone' => 'setTelephone',
        'address_row2' => 'setAddressRow2',
        'chamber_of_commerce' => 'setChamberOfCommerce',
        'fullstreet' => 'setFullstreet',
        'first_name' => 'setFirstName',
        'is_vat_validated' => 'setIsVatValidated',
        'id' => 'setId',
        'email' => 'setEmail'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'country' => 'getCountry',
        'invalid_use_anyway' => 'getInvalidUseAnyway',
        'last_name' => 'getLastName',
        'city' => 'getCity',
        'is_valid' => 'getIsValid',
        'sticky_slip_image_id' => 'getStickySlipImageId',
        'postcode' => 'getPostcode',
        'telephone' => 'getTelephone',
        'address_row2' => 'getAddressRow2',
        'chamber_of_commerce' => 'getChamberOfCommerce',
        'fullstreet' => 'getFullstreet',
        'first_name' => 'getFirstName',
        'is_vat_validated' => 'getIsVatValidated',
        'id' => 'getId',
        'email' => 'getEmail'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['country'] = isset($data['country']) ? $data['country'] : null;
        $this->container['invalid_use_anyway'] = isset($data['invalid_use_anyway']) ? $data['invalid_use_anyway'] : null;
        $this->container['last_name'] = isset($data['last_name']) ? $data['last_name'] : null;
        $this->container['city'] = isset($data['city']) ? $data['city'] : null;
        $this->container['is_valid'] = isset($data['is_valid']) ? $data['is_valid'] : null;
        $this->container['sticky_slip_image_id'] = isset($data['sticky_slip_image_id']) ? $data['sticky_slip_image_id'] : null;
        $this->container['postcode'] = isset($data['postcode']) ? $data['postcode'] : null;
        $this->container['telephone'] = isset($data['telephone']) ? $data['telephone'] : null;
        $this->container['address_row2'] = isset($data['address_row2']) ? $data['address_row2'] : null;
        $this->container['chamber_of_commerce'] = isset($data['chamber_of_commerce']) ? $data['chamber_of_commerce'] : null;
        $this->container['fullstreet'] = isset($data['fullstreet']) ? $data['fullstreet'] : null;
        $this->container['first_name'] = isset($data['first_name']) ? $data['first_name'] : null;
        $this->container['is_vat_validated'] = isset($data['is_vat_validated']) ? $data['is_vat_validated'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['country'] === null) {
            $invalidProperties[] = "'country' can't be null";
        }
        if ($this->container['last_name'] === null) {
            $invalidProperties[] = "'last_name' can't be null";
        }
        if ($this->container['city'] === null) {
            $invalidProperties[] = "'city' can't be null";
        }
        if ($this->container['postcode'] === null) {
            $invalidProperties[] = "'postcode' can't be null";
        }
        if ($this->container['telephone'] === null) {
            $invalidProperties[] = "'telephone' can't be null";
        }
        if ($this->container['fullstreet'] === null) {
            $invalidProperties[] = "'fullstreet' can't be null";
        }
        if ($this->container['first_name'] === null) {
            $invalidProperties[] = "'first_name' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string $country country
     *
     * @return $this
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets invalid_use_anyway
     *
     * @return bool
     */
    public function getInvalidUseAnyway()
    {
        return $this->container['invalid_use_anyway'];
    }

    /**
     * Sets invalid_use_anyway
     *
     * @param bool $invalid_use_anyway invalid_use_anyway
     *
     * @return $this
     */
    public function setInvalidUseAnyway($invalid_use_anyway)
    {
        $this->container['invalid_use_anyway'] = $invalid_use_anyway;

        return $this;
    }

    /**
     * Gets last_name
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     *
     * @param string $last_name last_name
     *
     * @return $this
     */
    public function setLastName($last_name)
    {
        $this->container['last_name'] = $last_name;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string $city city
     *
     * @return $this
     */
    public function setCity($city)
    {
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets is_valid
     *
     * @return bool
     */
    public function getIsValid()
    {
        return $this->container['is_valid'];
    }

    /**
     * Sets is_valid
     *
     * @param bool $is_valid is_valid
     *
     * @return $this
     */
    public function setIsValid($is_valid)
    {
        $this->container['is_valid'] = $is_valid;

        return $this;
    }

    /**
     * Gets sticky_slip_image_id
     *
     * @return string
     */
    public function getStickySlipImageId()
    {
        return $this->container['sticky_slip_image_id'];
    }

    /**
     * Sets sticky_slip_image_id
     *
     * @param string $sticky_slip_image_id sticky_slip_image_id
     *
     * @return $this
     */
    public function setStickySlipImageId($sticky_slip_image_id)
    {
        $this->container['sticky_slip_image_id'] = $sticky_slip_image_id;

        return $this;
    }

    /**
     * Gets postcode
     *
     * @return string
     */
    public function getPostcode()
    {
        return $this->container['postcode'];
    }

    /**
     * Sets postcode
     *
     * @param string $postcode postcode
     *
     * @return $this
     */
    public function setPostcode($postcode)
    {
        $this->container['postcode'] = $postcode;

        return $this;
    }

    /**
     * Gets telephone
     *
     * @return string
     */
    public function getTelephone()
    {
        return $this->container['telephone'];
    }

    /**
     * Sets telephone
     *
     * @param string $telephone telephone
     *
     * @return $this
     */
    public function setTelephone($telephone)
    {
        $this->container['telephone'] = $telephone;

        return $this;
    }

    /**
     * Gets address_row2
     *
     * @return string
     */
    public function getAddressRow2()
    {
        return $this->container['address_row2'];
    }

    /**
     * Sets address_row2
     *
     * @param string $address_row2 address_row2
     *
     * @return $this
     */
    public function setAddressRow2($address_row2)
    {
        $this->container['address_row2'] = $address_row2;

        return $this;
    }

    /**
     * Gets chamber_of_commerce
     *
     * @return string
     */
    public function getChamberOfCommerce()
    {
        return $this->container['chamber_of_commerce'];
    }

    /**
     * Sets chamber_of_commerce
     *
     * @param string $chamber_of_commerce chamber_of_commerce
     *
     * @return $this
     */
    public function setChamberOfCommerce($chamber_of_commerce)
    {
        $this->container['chamber_of_commerce'] = $chamber_of_commerce;

        return $this;
    }

    /**
     * Gets fullstreet
     *
     * @return string
     */
    public function getFullstreet()
    {
        return $this->container['fullstreet'];
    }

    /**
     * Sets fullstreet
     *
     * @param string $fullstreet fullstreet
     *
     * @return $this
     */
    public function setFullstreet($fullstreet)
    {
        $this->container['fullstreet'] = $fullstreet;

        return $this;
    }

    /**
     * Gets first_name
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     *
     * @param string $first_name first_name
     *
     * @return $this
     */
    public function setFirstName($first_name)
    {
        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets is_vat_validated
     *
     * @return bool
     */
    public function getIsVatValidated()
    {
        return $this->container['is_vat_validated'];
    }

    /**
     * Sets is_vat_validated
     *
     * @param bool $is_vat_validated is_vat_validated
     *
     * @return $this
     */
    public function setIsVatValidated($is_vat_validated)
    {
        $this->container['is_vat_validated'] = $is_vat_validated;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


