<?php
/**
 * CustomSizesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Print-Gateway-prod
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-09-18T08:39:50Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CustomSizesTest Class Doc Comment
 *
 * @category    Class
 * @description Only available for the option &#39;custom&#39; for property &#39;size&#39; Specifies size limits of custom sizes
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomSizesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomSizes"
     */
    public function testCustomSizes()
    {
    }

    /**
     * Test attribute "min_height"
     */
    public function testPropertyMinHeight()
    {
    }

    /**
     * Test attribute "max_height"
     */
    public function testPropertyMaxHeight()
    {
    }

    /**
     * Test attribute "min_width"
     */
    public function testPropertyMinWidth()
    {
    }

    /**
     * Test attribute "max_width"
     */
    public function testPropertyMaxWidth()
    {
    }
}
