<?php
/**
 * OrderResponseModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Print-Gateway-prod
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-09-18T08:39:50Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderResponseModelTest Class Doc Comment
 *
 * @category    Class
 * @description OrderResponseModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderResponseModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderResponseModel"
     */
    public function testOrderResponseModel()
    {
    }

    /**
     * Test attribute "order_number"
     */
    public function testPropertyOrderNumber()
    {
    }

    /**
     * Test attribute "grand_total"
     */
    public function testPropertyGrandTotal()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "order_tax"
     */
    public function testPropertyOrderTax()
    {
    }

    /**
     * Test attribute "shipments"
     */
    public function testPropertyShipments()
    {
    }

    /**
     * Test attribute "order_total"
     */
    public function testPropertyOrderTotal()
    {
    }

    /**
     * Test attribute "shipping_price"
     */
    public function testPropertyShippingPrice()
    {
    }

    /**
     * Test attribute "customer_reference"
     */
    public function testPropertyCustomerReference()
    {
    }

    /**
     * Test attribute "order_due"
     */
    public function testPropertyOrderDue()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "invoice_id"
     */
    public function testPropertyInvoiceId()
    {
    }

    /**
     * Test attribute "billing_address"
     */
    public function testPropertyBillingAddress()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
    }

    /**
     * Test attribute "po_number"
     */
    public function testPropertyPoNumber()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
