<?php
/**
 * OrderResponseModelItemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Print-Gateway-prod
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-09-18T08:39:50Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderResponseModelItemsTest Class Doc Comment
 *
 * @category    Class
 * @description OrderResponseModelItems
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderResponseModelItemsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderResponseModelItems"
     */
    public function testOrderResponseModelItems()
    {
    }

    /**
     * Test attribute "has_sticky_slip"
     */
    public function testPropertyHasStickySlip()
    {
    }

    /**
     * Test attribute "sender_address"
     */
    public function testPropertySenderAddress()
    {
    }

    /**
     * Test attribute "order_number"
     */
    public function testPropertyOrderNumber()
    {
    }

    /**
     * Test attribute "print_coupon"
     */
    public function testPropertyPrintCoupon()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "order_item_id"
     */
    public function testPropertyOrderItemId()
    {
    }

    /**
     * Test attribute "sales_price"
     */
    public function testPropertySalesPrice()
    {
    }

    /**
     * Test attribute "delivery_promise"
     */
    public function testPropertyDeliveryPromise()
    {
    }

    /**
     * Test attribute "sales_price_incl_tax"
     */
    public function testPropertySalesPriceInclTax()
    {
    }

    /**
     * Test attribute "shipments"
     */
    public function testPropertyShipments()
    {
    }

    /**
     * Test attribute "discount_percentage"
     */
    public function testPropertyDiscountPercentage()
    {
    }

    /**
     * Test attribute "printjob_id"
     */
    public function testPropertyPrintjobId()
    {
    }

    /**
     * Test attribute "shipping_price"
     */
    public function testPropertyShippingPrice()
    {
    }

    /**
     * Test attribute "service_price"
     */
    public function testPropertyServicePrice()
    {
    }

    /**
     * Test attribute "customer_reference"
     */
    public function testPropertyCustomerReference()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "normal_price"
     */
    public function testPropertyNormalPrice()
    {
    }

    /**
     * Test attribute "options"
     */
    public function testPropertyOptions()
    {
    }

    /**
     * Test attribute "order_item_number"
     */
    public function testPropertyOrderItemNumber()
    {
    }

    /**
     * Test attribute "delivery_promise_price"
     */
    public function testPropertyDeliveryPromisePrice()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "product_price"
     */
    public function testPropertyProductPrice()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
