<?php
/**
 * Price1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Print-Gateway-prod
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-09-18T08:39:50Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * Price1Test Class Doc Comment
 *
 * @category    Class
 * @description Price1
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Price1Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Price1"
     */
    public function testPrice1()
    {
    }

    /**
     * Test attribute "urgency_minimum_price"
     */
    public function testPropertyUrgencyMinimumPrice()
    {
    }

    /**
     * Test attribute "urgency"
     */
    public function testPropertyUrgency()
    {
    }

    /**
     * Test attribute "urgency_price_percentage"
     */
    public function testPropertyUrgencyPricePercentage()
    {
    }

    /**
     * Test attribute "base"
     */
    public function testPropertyBase()
    {
    }
}
