<?php
/**
 * PricesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Print-Gateway-prod
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-09-18T08:39:50Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PricesTest Class Doc Comment
 *
 * @category    Class
 * @description Prices
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PricesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Prices"
     */
    public function testPrices()
    {
    }

    /**
     * Test attribute "discount_percentage"
     */
    public function testPropertyDiscountPercentage()
    {
    }

    /**
     * Test attribute "urgency_price"
     */
    public function testPropertyUrgencyPrice()
    {
    }

    /**
     * Test attribute "agreement_price_type"
     */
    public function testPropertyAgreementPriceType()
    {
    }

    /**
     * Test attribute "sales_price"
     */
    public function testPropertySalesPrice()
    {
    }

    /**
     * Test attribute "normal_price"
     */
    public function testPropertyNormalPrice()
    {
    }

    /**
     * Test attribute "delivery_promise_price"
     */
    public function testPropertyDeliveryPromisePrice()
    {
    }

    /**
     * Test attribute "product_price"
     */
    public function testPropertyProductPrice()
    {
    }
}
