<?php
/**
 * ContactApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Print-Gateway-prod
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-09-18T08:39:50Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ContactApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContactApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for contactsGet
     *
     * .
     *
     */
    public function testContactsGet()
    {
    }

    /**
     * Test case for contactsIdDelete
     *
     * .
     *
     */
    public function testContactsIdDelete()
    {
    }

    /**
     * Test case for contactsIdPut
     *
     * Update contact.
     *
     */
    public function testContactsIdPut()
    {
    }

    /**
     * Test case for contactsPost
     *
     * New contact.
     *
     */
    public function testContactsPost()
    {
    }

    /**
     * Test case for placesGet
     *
     * Get address.
     *
     */
    public function testPlacesGet()
    {
    }

    /**
     * Test case for placesSearchGet
     *
     * Find address.
     *
     */
    public function testPlacesSearchGet()
    {
    }

    /**
     * Test case for placesSuggestionsGet
     *
     * Address suggestions.
     *
     */
    public function testPlacesSuggestionsGet()
    {
    }

    /**
     * Test case for placesValidatePost
     *
     * Validate address.
     *
     */
    public function testPlacesValidatePost()
    {
    }
}
